#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# `setuid` doesn't work in scripts, so we allow every user to `sudo` into the
# `github-app-credentials` user to execute the actual script.
sudo -u github-app-credentials /home/github-app-credentials/bin/git-credential-dev-desktop-inner $@
