#!/usr/bin/env bash
set -euo pipefail

remote="${REMOTE:-origin}"
base_branch="${BASE_BRANCH:-master}"
branch_prefix="${STACK_PREFIX:-rustc-perf/graviton5}"
dry_run="${DRY_RUN:-0}"

subjects=(
  "Provision rustc-perf-prod AWS account"
  "Bootstrap the rustc-perf-prod account"
  "Provision the Graviton 5 rustc-perf collector"
  "Document the rustc-perf rollout and PR stack"
)

branches=(
  "${branch_prefix}-1-account"
  "${branch_prefix}-2-bootstrap"
  "${branch_prefix}-3-collector"
  "${branch_prefix}-4-runbook"
)

titles=(
  "Provision the rustc-perf-prod AWS account"
  "Bootstrap the rustc-perf-prod AWS account"
  "Provision the Graviton 5 rustc-perf collector"
  "Document the rustc-perf-prod rollout"
)

bodies=(
  $'Creates the `rustc-perf-prod` AWS Organizations account and assigns the existing infrastructure administrator and read-only roles.\n\nStack: 1/4.'
  $'Adds the new Terragrunt account baseline, Datadog and Wiz integrations, and the M9g Dedicated Host quota request required by the collector.\n\nStack: 2/4. Depends on the account PR.'
  $'Allocates an M9g Dedicated Host and places a no-ingress `m9g.12xlarge` Graviton 5 collector on it, with SSM access, host recovery, termination protection, encrypted storage, and a boot-time hardware performance-counter smoke test.\n\nStack: 3/4. Depends on the account bootstrap PR and an approved host quota increase.'
  $'Documents the ordered rollout and PMU verification procedure, and adds the reproducible script used to publish this PR stack.\n\nStack: 4/4. Depends on the collector PR.'
)

# Define the disclosure once so newly created and subsequently updated PRs all
# receive identical wording.
ai_disclosure=$'- [ ] This PR was generated by AI and I haven\'t reviewed it yet. Please don\'t waste your time reading it yet.\n\n## AI disclosure\n\nI used GPT5.6-Sol with the codex harness to generate this change. I reviewed its output and changed it where necessary.'

if ! command -v git >/dev/null 2>&1; then
  echo "error: git is required" >&2
  exit 1
fi

if [[ "$dry_run" != 1 ]]; then
  if ! command -v gh >/dev/null 2>&1; then
    echo "error: gh is required" >&2
    exit 1
  fi
  gh auth status >/dev/null
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "error: commit or stash worktree changes before publishing the stack" >&2
  exit 1
fi

if [[ "$dry_run" != 1 ]]; then
  git fetch --prune "$remote"
fi

base_ref="$remote/$base_branch"
if ! git rev-parse --verify --quiet "$base_ref" >/dev/null; then
  echo "error: base ref $base_ref does not exist" >&2
  exit 1
fi

commits=()
for subject in "${subjects[@]}"; do
  matches="$(git log --format=$'%H\t%s' "$base_ref..HEAD" | awk -F $'\t' -v subject="$subject" '$2 == subject { print $1 }')"
  if [[ "$(wc -w <<<"$matches")" -ne 1 ]]; then
    echo "error: expected one commit named '$subject' after $base_ref" >&2
    exit 1
  fi
  commits+=("$matches")
done

expected_parent="$(git rev-parse "$base_ref")"
for commit in "${commits[@]}"; do
  actual_parent="$(git rev-parse "$commit^")"
  if [[ "$actual_parent" != "$expected_parent" ]]; then
    echo "error: the four stack commits must be contiguous and based on $base_ref" >&2
    exit 1
  fi
  expected_parent="$commit"
done

urls=()
pr_base="$base_branch"

for index in "${!commits[@]}"; do
  branch="${branches[$index]}"
  commit="${commits[$index]}"

  if [[ "$dry_run" == 1 ]]; then
    echo "$commit -> $branch (base: $pr_base)"
    pr_base="$branch"
    continue
  fi

  git push \
    --force-with-lease="refs/heads/$branch" \
    "$remote" \
    "$commit:refs/heads/$branch"

  if url="$(gh pr view "$branch" --json url --jq .url 2>/dev/null)"; then
    gh pr edit "$url" \
      --base "$pr_base" \
      --title "${titles[$index]}" \
      --body "${bodies[$index]}"$'\n\n'"$ai_disclosure" >/dev/null
  else
    url="$(gh pr create \
      --base "$pr_base" \
      --head "$branch" \
      --title "${titles[$index]}" \
      --body "${bodies[$index]}"$'\n\n'"$ai_disclosure")"
  fi

  urls+=("$url")
  pr_base="$branch"
done

if [[ "$dry_run" == 1 ]]; then
  echo "Dry run only; no branches were pushed and no PRs were changed."
  exit 0
fi

echo "Published rustc-perf PR stack:"
printf '  %s\n' "${urls[@]}"
