---

- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 14400  # 4 hours

- name: install apt packages
  apt:
    name:
      # - aptitude  # needed by ansible itself
      - ca-certificates
      - htop
      - iptables
      - openssh-server
      - python3
      - python3-apt
      - vim
      - rsyslog-gnutls  # needed for papertrail
    state: present
