#!/usr/bin/python

from sys import argv, stdin
import os

if argv[1] != "get":
    exit(0)

config = [x.strip() for x in stdin]

if config[1] != "host=github.com":
    exit(0)

path = config[2].split('=')
path = path[1].split('/')

# Get the username of the caller, not the owner of
# this script (which is setuid)
user = os.getlogin()
if user.startswith("gh-"):
    user = user[3:]

# we don't support usernames differing from repo owner names for now
if user != path[0]:
    exit(0)
repo = path[1].rsplit('.', 1)[0]

real_path = os.path.realpath(__file__)
dir_path = os.path.dirname(real_path)

from dump import token

for config in config:
    print(config)

print(f"username={user}")

print(f"password={token(user, repo)}")
print()

