name: 'Deploy static website'
description: 'Deploy a static website on Rust infrastructure'

inputs:
  deploy_dir:
    description: 'Directory to deploy'
    required: true
  github_token:
    description: 'GitHub token used to push the website'
    required: true
  cloudfront_distribution:
    description: 'Cloudfront distribution to invalidate'
    required: false
    default: ''
  aws_access_key_id:
    description: 'AWS IAM credentials used to invalidate Cloudfront'
    required: false
    default: ''
  aws_secret_access_key:
    description: 'AWS IAM credentials used to invalidate Cloudfront'
    required: false
    default: ''
  custom_domain:
    description: 'The custom domain for GitHub Pages'
    required: false
    default: ''

runs:
  using: docker
  image: Dockerfile
