on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rust:
    name: Rust projects
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        run: rustup update stable && rustup default stable && rustup component add clippy rustfmt

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run the test suite
        run: cargo test --all

      - name: Run clippy
        run: cargo clippy --all -- -Dwarnings

  static-crates-io:
    name: static.crates.io Fastly worker
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=crate depName=viceroy
      VICEROY_VERSION: "0.20.0"
      # renovate: datasource=crate depName=cargo-nextest
      NEXTEST_VERSION: "0.9.140"
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: VICEROY_VERSION NEXTEST_VERSION
          workspaces: terragrunt/modules/crates-io/compute-static

      - name: Install test tools
        run: |
          cargo install viceroy --locked --version "$VICEROY_VERSION"
          cargo install cargo-nextest --locked --version "$NEXTEST_VERSION"

      - name: Run the test suite
        working-directory: terragrunt/modules/crates-io/compute-static
        run: cargo nextest run

  terraform:
    name: Terraform configuration
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install terraform cli
        uses: hashicorp/setup-terraform@v3

      - name: Ensure the terraform files are formatted correctly
        run: terraform fmt -check -diff -recursive

  actions-js:
    name: GitHub Actions (JS)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Ensure the bundled action is the same as the source code
        run: |
          for action in $(ls github-actions/); do
            if [[ -f "github-actions/${action}/package.json" ]]; then
              pushd "github-actions/${action}"
              sha256sum dist/* > "/tmp/sha256-${action}-before"
              npm install
              npm run build
              sha256sum dist/* > "/tmp/sha256-${action}-after"
              diff -u --color "/tmp/sha256-${action}-before" "/tmp/sha256-${action}-after"
              popd
            fi
          done

  javascript-tests:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Run tests
        run: |
          node --test terragrunt/modules/release-distribution/lambdas/doc-router/test.mjs
